name: 📦 Build Flatpak

on:
  push:
    branches: [main]
  pull_request:

jobs:
  flatpak:
    name: build-flatpak
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-22.08
      options: --privileged
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: "true"
      - name: Build Flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v4
        with:
          bundle: gg.minion.Minion.flatpak
          manifest-path: gg.minion.Minion.yml
          cache-key: flatpak-builder-${{ github.sha }}
          branch: stable
      - name: Deploy
        if: github.event_name != 'pull_request'
        uses: flatpak/flatpak-github-actions/flat-manager@v3
        with:
          repository: ""
          flat-manager-url: https://flatpak.hachiman.nils.moe
          token: ${{ secrets.FLATMAN_TOKEN }}
